### PR TITLE
Borrow requests

### LINKED ISSUE #52: As a gamer, I want to be able to send a borrow request for a game, so that I can easily ask game owners to borrow their games
- [ ] Send a request to borrow a game from the owner with the following information
- - [ ] the user that borrows the game
- - [ ] the date which the game is going to be borrowed
- - [ ] the expected return date(?)
- [ ] A view for the owner to see the all their borrow requests

### PR DESCRIPTION
**Pull request by GAsplund**
## Key features
- API backend for sending, listing and responding to borrow requests
- UI for requesting (or immediately if permissions allow) to borrow games
- UI for listing and responding to requests
- Basic checks for making sure that someone cannot request to borrow when a request is already planned
- Closes #52 

## Known issues
- Since no users exist in the `main` branch yet, users always default to the name "User"
- Since no ownership/management for games exists in `main` yet, all active requests are listed regardless
- Username is sent from the client, allowing spoofing (no users middleware)
- While logic exists for both immediately borrowing and requesting to borrow, it's assumed that the user does not have privileges to immediately borrow any game (no ownership/management)
- Games will not be automatically borrowed when they enter their borrow period (allow the user to manually borrow when their time period is in?)

I deem these issues to be outside the scope for #52 but should be prioritised to be solved at a later time.

Also, please squash when merging :)

### CODE REVIEW

**Review by Krysset — COMMENTED** [review]
Good job! Only issue is that date restrictions are a bit lacking. For example I can request to borrow a game starting a week ago and end yesterday.

**Comment by GAsplund** [comment]
> Good job! Only issue is that date restrictions are a bit lacking. For example I can request to borrow a game starting a week ago and end yesterday. Might not count as a part of this PR though

I think having some level of fail-safety/checks should exist in most PRs, so I've gone ahead and implemented some checks for proper dates.

**Review by Krysset — APPROVED** [review]
Works great! LGTM

**Review by x183 — APPROVED** [review]
LGTM :heart:

**Pull request merged**
