### PR TITLE
Feature/scss setup

### PR DESCRIPTION
**Pull request by x183**
Added global variables to use in project

### CODE REVIEW

**Comment by x183** [comment]
WHY DOES EVERY PAGE USE THE SAME CSS MODULE!!!!?
PUTH THE FUNCTIONALITY IN A GLOBAL FILE INSTEAD

**Review by Oscariremma — APPROVED** [review]
Yes

**Review by GAsplund — APPROVED** [review]
yea yea looks good and all that

**Comment by x183** [comment]
plz squash when merge <3

**Pull request merged**
